---
title: "ST303 group project"
output: html_document
date: "2025-04-04"
---

## Question 3

### (a)
```{r}
set.seed(1)
T = 10
N = 1000
dt = T/N
Rt_sim <- function(delta, N, dt){
  Y <- numeric(N+1)
  Y[1] <- 1
  for (i in 1:N){
    dW <- sqrt(dt)*rnorm(1)
    Y[i+1] <- max(Y[i] + delta*dt+ 2*sqrt(Y[i])*dW, 0)
  } 
  return(sqrt(Y))
}
t <- seq(0, T, by = dt)
delta <- c(1,2,3,4)
Rt1 <- Rt_sim(delta[1], N=1000, dt=10/1000)
Rt2 <- Rt_sim(delta[2], N=1000, dt=10/1000)
Rt3 <- Rt_sim(delta[3], N=1000, dt=10/1000)
Rt4 <- Rt_sim(delta[4], N=1000, dt=10/1000)
ymin <- min(c(Rt1, Rt2, Rt3, Rt4))
ymax <- max(c(Rt1, Rt2, Rt3, Rt4))
plot(t, Rt1, "l", col = "yellow", ylim = c(ymin, ymax), main = "Sample Paths of Bessel Process", xlab = "Time t", ylab = expression(R[t]))
lines(t, Rt2, "l", col="red")
lines(t, Rt3, "l", col="blue")
lines(t, Rt4, "l", col="green")
legend("topleft",
       legend = c(expression(delta *' = 1'), expression(delta *' = 2'), expression(delta *' = 3'), expression(delta *' = 4')),
       col = c("yellow", "red", "blue", "green"),
       lty = 1)  
```

### (b)
```{r}
set.seed(1)
par(mfrow = c(2,2))

M <- 100  # Number of sample paths
t <- seq(0, T, by = dt)

# choose delta = 1, generate more paths
Rt_matrix <- sapply(1:M, function(m) Rt_sim(delta[1], N, dt)) # row: dt, col: Rt

matplot(t, Rt_matrix, type = "l", lty = 1, col = rainbow(M),
        main = "Sample Paths of Bessel Process (δ = 1)",
        xlab = "Time t", ylab = expression(R[t]))

max_Rt <- apply(Rt_matrix, 2, max) # calculate maximum for each column of Rt_matrix

hist(max_Rt, breaks = 20, prob = T, 
     main = expression("Histogram of Max " * R[t] * " over [0,10] (δ = 1)"), 
     xlab = expression("Max " * R[t]))

mean(max_Rt)
legend("topright",
       legend = "mean = 3.812538")
```

### (c)
```{r}
set.seed(1)

delta = 1.2
K = 2
T = 10
M <- 100  # Number of sample paths
t <- seq(0, T, by = dt)

Rt_matrix <- sapply(1:M, function(m) Rt_sim(delta, N, dt)) # row: dt, col: mth path of Rt

matplot(t, Rt_matrix, type = "l", lty = 1, col = rainbow(M),
        main = "Sample Paths of Bessel Process (δ = 1.2)",
        xlab = "Time t", ylab = expression(R[t]))




tk_index <- (1:10)/(10/1000) +1
Rtk <- Rt_matrix[tk_index, ]  # rows: t_k, cols: paths

tk_payoff <- pmax(Rtk - K, 0)  # (Rt - K)+

exercise_time <- apply(tk_payoff, 2, function(payoffs) {
  idx <- which(payoffs > 0)[1]  # first positive payoff
  if (is.na(idx)) return(NA)   # never exercised
  return(idx)  # tk index (1 to 10)
})

# Convert index to actual time τ
tau <- ifelse(is.na(exercise_time), NA, exercise_time)  # τ in 1:10
```








