---
title: "Q2 Analaysis"
output: html_document
date: "2025-04-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Upload data
```{r}
library(tidyverse)
Q2_summary <- read.csv('Q2_summary_10_param.csv')

Q2_summary
colnames(Q2_summary)
```

### Mean analysis
```{r}
Q2_summary_mean <- Q2_summary %>% select(
  m, nu, lambda, alpha, theoretical_mean, 
  envelope_1 = envelop_1_empirical_mean,
  envelope_3 = envelop_3_empirical_mean,
  envelope_4 = envelop_4_empirical_mean,
  envelope_5 = envelop_5_empirical_mean,
) %>% mutate(
  diff_1 = envelope_1 - theoretical_mean,
  diff_3 = envelope_3 - theoretical_mean,
  diff_4 = envelope_4 - theoretical_mean,
  diff_5 = envelope_5 - theoretical_mean
)

Q2_summary_mean
```

### Variance analysis
```{r}
Q2_summary_var <- Q2_summary %>% select(
  m, nu, lambda, alpha, theoretical_var, 
  envelope_1 = envelop_1_empirical_var,
  envelope_3 = envelop_3_empirical_var,
  envelope_4 = envelop_4_empirical_var,
  envelope_5 = envelop_5_empirical_var,
) %>% mutate(
  diff_1 = envelope_1 - theoretical_var,
  diff_3 = envelope_3 - theoretical_var,
  diff_4 = envelope_4 - theoretical_var,
  diff_5 = envelope_5 - theoretical_var
)

Q2_summary_var
```

## Acceptance analysis
```{r}
Q2_summary_acceptance <- Q2_summary %>% select(
  m, nu, lambda, alpha,
  envelope_1 = envelope_1_empirical_acceptance,
  envelope_3 = envelope_3_empirical_acceptance,
  envelope_4 = envelope_4_empirical_acceptance,
  envelope_5 = envelope_5_empirical_acceptance,
)

Q2_summary_acceptance
```

### Export the analysis
```{r}
# write.csv(Q2_summary_mean, 'Q2_summary_mean_10_param.csv')
# write.csv(Q2_summary_var, 'Q2_summary_var_10_param.csv')
# write.csv(Q2_summary_acceptance, 'Q2_summary_acceptance_10_param.csv')
```

### Further analysis on acceptance rate
```{r}
library(ggplot2)
library(tidyr)

# Convert wide dataframe to long format
df_long <- pivot_longer(Q2_summary_acceptance[, 5:ncol(Q2_summary_acceptance)], cols = everything(), names_to = "Envelope", values_to = "Acceptance")

# Plot
ggplot(df_long, aes(x = Envelope, y = Acceptance, fill = Envelope)) +
  geom_boxplot() +
  theme_minimal() + 
  theme(legend.position = "none")
```

